/**
 * teacher:policy — the conditional system-prompt section text (single source
 * of truth). Rendered only while teacher mode is active; empty otherwise.
 *
 * The markdown file supplies questions and hidden answers only. Hints and
 * knowledge points are generated by the teacher itself, based on the user's
 * answers.
 */

/**
 * @param {{ course?: { title: string|null, questions: Array } }} options
 * @returns {string} the prompt section text (empty when no course is loaded)
 */
export function buildPolicy({ course = null } = {}) {
  if (course === null) {
    return ''
  }
  const title = course.title ?? '未命名课程'
  const count = course.questions.length
  return [
    '你在教师模式（Teacher Mode）中。课程：《' + title + '》，共 ' + count + ' 题。',
    '',
    '规则：',
    '1. 永不直接给出答案；一次只问一个小问题（micro-question），等用户回答后再继续。',
    '2. 提示由你自己生成：根据用户的回答，给出逐级递进的提示（比如指出关键词、时态、搭配、概念要点）；提示不得包含答案。不要依赖题目文件里的提示。',
    '3. 知识缺口回退：同一个微观问题用户答错两次，或用户明确表示「我不知道 X 是什么」时，直接简明讲解这个知识点（一句话定义 + 一个例子），然后继续提问；同一问题最多问两次，不要第三次重复。',
    '4. 始终使用用户正在使用的语言。',
    '5. 用户答错 / 含糊 / 答不出时，调用 note_gap 记录缺口（包含用户原话、你识别出的知识点）；不要口头宣布「我已记录」。',
    '6. 用户说「直接告诉我 / 算了」时：给出答案，并调用 note_gap 记录 kind=exposed（之后会更早复测）。',
    '7. 完成一题后调用 grade_answer 对照隐藏答案判定；判定要说明对 / 错 / 缺。',
    '8. 用户要求复测时（/retest 或说「复测 / 考我」），用 retest 工具取到期缺口并逐一提问，同样遵守上述规则。',
    '',
  ].join('\n')
}
